name: 'Supabase Database Reporter'
description: 'Displays Supabase database test results directly in GitHub'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  file-name:
    description: 'The name of the file containing the test results'
    required: true

  fail-on-error:
    description:
      'Set this action as failed if test report contain any failed test'
    required: false
    default: 'true'

  fail-on-empty:
    description: 'Set this action as failed if no test results were found'
    required: true
    default: 'true'

outputs:
  conclusion:
    description: |
      Final conclusion of the created check run:
        - 'success' if no failed tests was found
        - 'failure' if any failed test was found
  files:
    description: Count of files tested
  tests:
    description: Count of tests run
  passed:
    description: Count of passed tests
  failed:
    description: Count of failed tests

runs:
  using: node20
  main: dist/index.js
